/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testebd;

/**
 *
 * @author nemes
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelnome = new javax.swing.JLabel();
        labelcodigo = new javax.swing.JLabel();
        labelqnt = new javax.swing.JLabel();
        botLista = new javax.swing.JButton();
        botCadastro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoQnt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelnome.setText("Nome:");
        getContentPane().add(labelnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        labelcodigo.setText("Código:");
        getContentPane().add(labelcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        labelqnt.setText("Qnt:");
        getContentPane().add(labelqnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        botLista.setText("Listar Produtos");
        botLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botListaActionPerformed(evt);
            }
        });
        getContentPane().add(botLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        botCadastro.setText("Cadastrar");
        botCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botCadastroMouseClicked(evt);
            }
        });
        botCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(botCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("CADASTRO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));
        getContentPane().add(campoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 131, 54, -1));

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 131, 92, -1));
        getContentPane().add(campoQnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 131, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void botListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botListaActionPerformed

    private void botCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botCadastroActionPerformed

    private void botCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCadastroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botCadastroMouseClicked

   
    public static void main(String args[]) {
        
        
         
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCadastro;
    private javax.swing.JButton botLista;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoQnt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labelnome;
    private javax.swing.JLabel labelqnt;
    // End of variables declaration//GEN-END:variables
}
